ClothingApp/Controllers/WeatherController.cs
using ClothingApp.Core.Services.WeatherService;
using ClothingApp.Data.Common.Models;
using ClothingApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClothingApp.Web.Controllers
{
    [ApiController]
    [Route("[controller]/[action]")]
    public class WeatherController : Controller
    {
        private readonly IWeatherService _weatherService;
        UserManager<ApplicationUser> _userManager;
        private string userCity;

        public WeatherController(IWeatherService weatherService, UserManager<ApplicationUser> userManager)
        {
            _weatherService = weatherService;
            _userManager = userManager;
        }

        private string GetCityByIP()
        {
            var remoteIpAddress = HttpContext.Connection.RemoteIpAddress.ToString();

            return _weatherService.GetCityName("46.0.40.18"); // ip adress
        }

        private async void GetCityFromUser()
        {
            if (this.User.Identity.IsAuthenticated)
            {
                ApplicationUser user = await _userManager.FindByNameAsync(this.User.Identity.Name);
                userCity =  user.City;
            }
            else userCity = "";

        }
        /// <summary>
        /// погода на 5 дней
        /// </summary>
        public List<Weather> GetWeatherForWeek()
        {
            string city = GetCityByIP();
            var respone = _weatherService.GetWeatherForFiveDays(city);

            return respone;

        }
        /// <summary>
        /// погода на сегодня
        /// </summary>
        /// <returns></returns>
        public List<Weather> GetWeatherToday()
        {
            string city = GetCityByIP();
            var respone = _weatherService.GetWeatherForToday(city);

            ViewBag.GetWeatherToday = respone;
            return respone;

        }
        
        /// <summary>
        /// погода на завтра
        /// </summary>
        /// <returns></returns>
        public List<Weather> GetWeatherTomorrow()
        {
            string city = GetCityByIP();
            var respone = _weatherService.GetWeatherForTomorrow(city);           

            return respone;

        }
        [HttpGet]
        public ActionResult Today()
        {
            GetCityFromUser();
            ViewBag.GetWeatherToday = GetWeatherToday();
            ViewBag.IsDifferentPlaces = false;
            if (GetCityByIP()!=userCity&&userCity!="")
            {
                ViewBag.IsDifferentPlaces = true;
            }
            return View("Today");
        }
        public ActionResult Tomorrow()
        {
            GetCityFromUser();
            ViewBag.GetWeatherTomorrow = GetWeatherTomorrow();
            ViewBag.IsDifferentPlaces = false;
            if (GetCityByIP() != userCity && userCity != "")
            {
                ViewBag.IsDifferentPlaces = true;
            }
            return View("Tomorrow");
        }
    }
}

ClothingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ClothingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>
    <header>       
            <div class="menu">
                <div class="form-search">
                    <input id="place" type="text" placeholder="Введите город">
                    <button class="btn" type="submit"></button>
                </div>
                <div class="menu-choice">
                    <a asp-area="" asp-controller="Weather" asp-action="Today" class="today">Сегодня</a>
                    <a asp-area="" asp-controller="Weather" asp-action="Tomorrow" class="tomorrow">Завтра</a>
                    <a class="week">Неделя</a>
                    <partial name="_LoginPartial" />
                </div>
                <div class="gender">
                    <div class="gender-item man">
                        <input id="fid-1" type="radio" name="radio" value="off" checked>
                        <label for="fid-1">М</label>
                    </div>
                    <div class="gender-item woman">
                        <input id="fid-2" type="radio" name="radio" value="on">
                        <label for="fid-2">Ж</label>
                    </div>
                </div>
            </div>                   
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>